README.md

Lists correct releases section and pip/git install link.

Updating README for version 1.0.0

---

appveyor.yml
boostsrl/rdn.py

*Concerns building/running/testing in a Windows environment.*
- Fix `os.waitpid` -> `_pid.wait()`
- Add `appveyor.yml` for running CI builds in a Windows environment
These changes allow the package to operate on Windows and Linux/Unix, and add a Windows build process via AppVeyor.

[MRG] 🏁 Windows compatibility

---

.github/CONTRIBUTING.md
README.rst
boostsrl/utils/_show_versions.py
boostsrl/utils/tests/test_show_versions.py
docs/notebooks/boostsrl-python-package-Introduction.ipynb
docs/source/api.rst
docs/source/index.rst
requirements.txt
setup.py

Fix deprecated `_get_blas_info()`
Fix urls to removed repositories

👽 Fixes for external API changes

---

.github/workflows/pythonpublish.yml

Add `.github/workflows/pythonpublish.yml`

✨ Create pythonpublish.yml

---

docs/source/conf.py
srlearn/background.py
srlearn/base.py
srlearn/boostsrl.py
srlearn/database.py
srlearn/rdn.py
srlearn/system_manager.py
srlearn/tests/test_background.py
srlearn/tests/test_system_manager.py

As per issue #25 I have removed all the TODO's I can find, opening new issues for each: no code only comments have changed so it should pass all tests

[MRG] Fixed Issue #25 by removing all TODO's in codebase

---

docs/source/index.rst

Add link emoji next to external links

Marking external links

---

srlearn/_meta.py

Summary of changes since last release:
- #38 - Removing TODOs from codebase
- #43 - Fixing delimiters used by `np.loadtxt` in `predict` and `predict_proba`
- #44 - Dropping Travis-CI and Circle-CI in favor of GitHub Actions

🚀 0.5.1 Release

---

docs/examples/plot_feature_importance.py
srlearn/base.py
srlearn/tests/test_rdn_feature_importances.py
srlearn/utils/_parse_trees.py
srlearn/utils/tests/test_parse_trees.py

Resolves #12 
Add `feature_importance` method to `srlearn.base`
Add `utils._parse_trees` class for handling model output files
Add tests / docs for some of these new features

[WIP] ✨ Feature Importance

---

.github/workflows/python_tests.yml

🐛 Fixing bug with python_tests.yml, not run on PR

---

.github/workflows/python_tests.yml
srlearn/base.py
srlearn/system_manager.py
srlearn/tests/test_serialize.py

Add `base.BaseBoostedRelationalModel.to_json`
Add `base.BaseBoostedRelationalModel.from_json`
Fixes #53 to help with saving/loading models
Minor fixes:
- Tests for serializing RDN objects (`BoostedRDN` and `BoostedRDNRegressor`)
- Bump version in `setup-java` to correct an error with using main as the default branch
- Docstrings with warnings about the stability of model saving/loading

[MRG] ✨ Serialization: to_json, from_json

---

.github/CONTRIBUTING.md
README.rst
docs/source/api.rst
docs/source/index.rst
srlearn/system_manager.py

✏️ Renaming master->main

---

srlearn/background.py

Fix #59 
Add `ok_if_unknown` option to `Background` object

✨ okIfUnknown in Background object

---

docs/source/api.rst
setup.py
srlearn/base.py
srlearn/plotting.py
srlearn/rdn.py
srlearn/system_manager.py
srlearn/tests/regression_tests/README.md

Fixes #56 
Fixes #28
Add `_get_dotfiles` method to `srlearn.base`
Add `srlearn.plotting` module
Add `srlearn.rdn` calls to `_get_dotfiles`
Add `srlearn.system_manager` awareness of `dotFiles` directory
Add directory for storing regression test data

[MRG] ✨ Plotting and exporting graphviz trees

---

docs/examples/plot_families.py
docs/examples/plot_feature_importance.py
docs/examples/plot_smokes_friends_cancer.py
srlearn/plotting.py

Rename `families` -> `plot_families`
Add output to `plot_families` showing probability of test-time `father` predicates

📝 More Documentation Auto Examples

---

requirements.txt

🚑️ Hotfix: Add `graphviz` to `requirements.txt`

---

README.rst
docs/examples/plot_families.py
docs/examples/plot_feature_importance.py
docs/examples/plot_smokes_friends_cancer.py
docs/source/api.rst
docs/source/getting_started.rst
docs/source/index.rst
docs/source/user_guide.rst
srlearn/background.py
srlearn/datasets/_toy_cancer.py
srlearn/plotting.py
srlearn/rdn.py
srlearn/system_manager.py

Fix toy dataset calls in auto examples following the modification that returned tuples instead of `sklearn.Bunch` objects

📝 Fix links, plot example fixes

---

.github/workflows/doc_tests.yml

On main push and pull requests, this runs a workflow to test sphinx docstrings with `make doctest`.
Passing means that the expected output matches across examples presented in the documentation.

👷 Add `doc_tests.yml` workflow to test docstrings

---

Makefile

🐛 Fix tests running in a reset environment

---

srlearn/base.py

Similar to what was done on `srlearn/background.py`, this reworks the
`_check_params` method in `srlearn/base.py` to check tuples.

🎨 Refactor if statements into tuples/loops

---

srlearn/database.py
srlearn/tests/test_database.py

Drop `add_pos`
Drop `add_neg`
Drop `add_fact`
YAGNI, Fix #22

🔥 Drop `add_pos`, etc. interface in `database`

---

srlearn/tests/test_rdn_regressor.py

Fix #106 
- Updates compiled `SRLBoost.jar` to `v0.2.0`
- Add a test to check that running regression doesn't throw an error (see commit message, Harsha noted some time back that regression was particularly unstable still #52)

🐛 Fix SRLBoost Regression

---

srlearn/rdn.py

👽️ Fix breaking calls to `np.loadtxt`
